// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer_message.proto

#include "transfer_message.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace transfer {
template <typename>
PROTOBUF_CONSTEXPR ResponseEmptyMessage::ResponseEmptyMessage(
    ::_pbi::ConstantInitialized) {}
struct ResponseEmptyMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResponseEmptyMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResponseEmptyMessageDefaultTypeInternal() {}
  union {
    ResponseEmptyMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResponseEmptyMessageDefaultTypeInternal _ResponseEmptyMessage_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR TransferMessage::TransferMessage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_name_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.message_content_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TransferMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TransferMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TransferMessageDefaultTypeInternal() {}
  union {
    TransferMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TransferMessageDefaultTypeInternal _TransferMessage_default_instance_;
}  // namespace transfer
static ::_pb::Metadata file_level_metadata_transfer_5fmessage_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_transfer_5fmessage_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_transfer_5fmessage_2eproto = nullptr;
const ::uint32_t TableStruct_transfer_5fmessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::transfer::ResponseEmptyMessage, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::transfer::TransferMessage, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::transfer::TransferMessage, _impl_.message_name_),
    PROTOBUF_FIELD_OFFSET(::transfer::TransferMessage, _impl_.message_content_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, -1, -1, sizeof(::transfer::ResponseEmptyMessage)},
        { 8, -1, -1, sizeof(::transfer::TransferMessage)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::transfer::_ResponseEmptyMessage_default_instance_._instance,
    &::transfer::_TransferMessage_default_instance_._instance,
};
const char descriptor_table_protodef_transfer_5fmessage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\026transfer_message.proto\022\010transfer\"\026\n\024Re"
    "sponseEmptyMessage\"@\n\017TransferMessage\022\024\n"
    "\014message_name\030\001 \001(\t\022\027\n\017message_content\030\002"
    " \001(\014b\006proto3"
};
static ::absl::once_flag descriptor_table_transfer_5fmessage_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_transfer_5fmessage_2eproto = {
    false,
    false,
    132,
    descriptor_table_protodef_transfer_5fmessage_2eproto,
    "transfer_message.proto",
    &descriptor_table_transfer_5fmessage_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_transfer_5fmessage_2eproto::offsets,
    file_level_metadata_transfer_5fmessage_2eproto,
    file_level_enum_descriptors_transfer_5fmessage_2eproto,
    file_level_service_descriptors_transfer_5fmessage_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_transfer_5fmessage_2eproto_getter() {
  return &descriptor_table_transfer_5fmessage_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_transfer_5fmessage_2eproto(&descriptor_table_transfer_5fmessage_2eproto);
namespace transfer {
// ===================================================================

class ResponseEmptyMessage::_Internal {
 public:
};

ResponseEmptyMessage::ResponseEmptyMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:transfer.ResponseEmptyMessage)
}
ResponseEmptyMessage::ResponseEmptyMessage(const ResponseEmptyMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  ResponseEmptyMessage* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:transfer.ResponseEmptyMessage)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ResponseEmptyMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ResponseEmptyMessage::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata ResponseEmptyMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_transfer_5fmessage_2eproto_getter, &descriptor_table_transfer_5fmessage_2eproto_once,
      file_level_metadata_transfer_5fmessage_2eproto[0]);
}
// ===================================================================

class TransferMessage::_Internal {
 public:
};

TransferMessage::TransferMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:transfer.TransferMessage)
}
TransferMessage::TransferMessage(const TransferMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TransferMessage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_name_) {}

    , decltype(_impl_.message_content_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.message_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.message_name_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message_name().empty()) {
    _this->_impl_.message_name_.Set(from._internal_message_name(), _this->GetArenaForAllocation());
  }
  _impl_.message_content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.message_content_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message_content().empty()) {
    _this->_impl_.message_content_.Set(from._internal_message_content(), _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:transfer.TransferMessage)
}

inline void TransferMessage::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.message_name_) {}

    , decltype(_impl_.message_content_) {}

    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.message_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.message_name_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.message_content_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.message_content_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TransferMessage::~TransferMessage() {
  // @@protoc_insertion_point(destructor:transfer.TransferMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TransferMessage::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_name_.Destroy();
  _impl_.message_content_.Destroy();
}

void TransferMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TransferMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:transfer.TransferMessage)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_name_.ClearToEmpty();
  _impl_.message_content_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TransferMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string message_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_message_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "transfer.TransferMessage.message_name"));
        } else {
          goto handle_unusual;
        }
        continue;
      // bytes message_content = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message_content();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* TransferMessage::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:transfer.TransferMessage)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string message_name = 1;
  if (!this->_internal_message_name().empty()) {
    const std::string& _s = this->_internal_message_name();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "transfer.TransferMessage.message_name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // bytes message_content = 2;
  if (!this->_internal_message_content().empty()) {
    const std::string& _s = this->_internal_message_content();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:transfer.TransferMessage)
  return target;
}

::size_t TransferMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:transfer.TransferMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message_name = 1;
  if (!this->_internal_message_name().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_message_name());
  }

  // bytes message_content = 2;
  if (!this->_internal_message_content().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
                                    this->_internal_message_content());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TransferMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TransferMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TransferMessage::GetClassData() const { return &_class_data_; }


void TransferMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TransferMessage*>(&to_msg);
  auto& from = static_cast<const TransferMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:transfer.TransferMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message_name().empty()) {
    _this->_internal_set_message_name(from._internal_message_name());
  }
  if (!from._internal_message_content().empty()) {
    _this->_internal_set_message_content(from._internal_message_content());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TransferMessage::CopyFrom(const TransferMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:transfer.TransferMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TransferMessage::IsInitialized() const {
  return true;
}

void TransferMessage::InternalSwap(TransferMessage* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_name_, lhs_arena,
                                       &other->_impl_.message_name_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_content_, lhs_arena,
                                       &other->_impl_.message_content_, rhs_arena);
}

::PROTOBUF_NAMESPACE_ID::Metadata TransferMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_transfer_5fmessage_2eproto_getter, &descriptor_table_transfer_5fmessage_2eproto_once,
      file_level_metadata_transfer_5fmessage_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace transfer
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::transfer::ResponseEmptyMessage*
Arena::CreateMaybeMessage< ::transfer::ResponseEmptyMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::transfer::ResponseEmptyMessage >(arena);
}
template<> PROTOBUF_NOINLINE ::transfer::TransferMessage*
Arena::CreateMaybeMessage< ::transfer::TransferMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::transfer::TransferMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
